---
name: Pedro
surname: Lima
position: "Buscando oportunidade na área de dados"
#date: "`r format(Sys.time(), '%B %Y')`"
address: "São Paulo-SP, `r format(Sys.time(), '%B %Y')`"
profilepic: "./img/eu.png"
phone: "(11) 9 7890-2956"
email: "cruz.ml.pedro@gmail.com"
github: cruz-ml-pedro
linkedin: pedro-lima-8a9356268
#orcid: 0000-0002-2114-966X
headcolor: 990000
aboutme: "Tive a oportunidade de atuar em diversas áreas, onde participei da utilização estratégica de dados. Minha jornada incluiu modelagem ambiental, onde apliquei dados para analisar impactos ambientais e criar modelos de dispersão de contaminantes. Como geofísico, estive envolvido na modelagem de dados para mapeamentos do subsolo e na investigação da interação entre atividade solar, magnetosfera e ionosfera, em relação aos fenômenos climáticos. Recentemente, no campo da ciência de dados, conduzi análises e criei modelos para otimizar estratégias e maximizar resultados de tráfego pago."
#docname: Pedro Lima
output: vitae::awesomecv
---
  
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
              ,'tibble'    # Data structure for tribbles
              ,'magrittr'  # The Pipe %>%
              ,'here'      # Relative File Paths
              ,'readr'     # Data Loading
              ,'glue'      # String Manipulation
)

xfun::pkg_attach2(packages, message = FALSE)

source(file = here("r","data.r"))

```

# Experiência Profissional

```{r EMPLOYMENT}

work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )

```

\pagebreak

# Experiência com pesquisa

```{r EXP PESQUISA}

research %>% 
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )


```


# Formação Acadêmica

```{r EDUCATION}

edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = glue::glue("{startYear} --> {endYear}",.na = ""),
    where = where
  )

```

# Tecnologias

```{r SKILLS}

skills %>%
  detailed_entries(
    with = area,
    what = skills
  )

```


# Tecnologias que sei o básico 
```{r BASICO}

basico %>% 
   detailed_entries(
    with = area,
    what = skills
  )

```

\pagebreak
# Tecnologias que estou aprendendo
```{r APRENDENDO}

aprendendo %>% 
   detailed_entries(
    with = area,
    what = skills
  )

```

# Habilidades e Competências

```{r HABILIDADES}
habilidades %>% 
   detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )


```


# Publicações

```{r WORKS}

Publicações %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )

```

